models:
  bs_roformer:
    source_repo: "https://github.com/ZFTurbo/Music-Source-Separation-Training.git"
    branch: "main"
    requirements_file: "requirements.txt" 
    target_dir: "models/zf_turbo"
    train_script: "train.py"
  